/*

!!INTER - CLIENT-SERVER COMMUNICATION & DATA - JSON - MAKING AN AJAX REQUEST TO ANOTHER DOMAIN (USING JSONP)!!

> You want to query for data using a web service API, such as the Rotten Tomatoes API,
or the Flicker API. However, the Ajax same-origin security policy prevents cross-domain
communication

*/

/*
SOLUTION STEPS:
> One approach is to use JSONP (JSON with padding) to work around the security issues

1) create a new script element, making the URL the endpoint for the API method call. 
The following creates a script element with a call to Flickr’s photo search API method
	> The URL looks like the following, including a request to return the data formatted as
	JSON, and providing a callback function name. The api_key is generated by Flickr, and
	the user_id is the unique user identifier, the NSID, for your account

2) I’m asking for the first page of results for a given user

> When the script tag is created, the request to Flickr is made, and because I passed in
the request for a JSON-formatted result and provided a callback function name, that’s
how the return is provided. 
3) The following is a basic callback function that just displays the results to the console
*/
1)
function addScript(url) {
	var script = document.createElement("script");
	script.type = "text/javascript";
	script.src = url,
	document.getElementsByTagName("head")[0].appendChild(script);
}

2)
http://api.flickr.com/services/rest/?method=flickr.photos.search&user_id=xxx
&api_key=xxx&page=1&format=json&jsoncallback=processPhotos

3)
function processPhotos(obj) {
	photos = obj.photos.photo;
	var str = '';
	
	photos.forEach(function(photo) {
		str += photo.title + '<br />';
	});
	document.getElementById('result').innerHTML = str;
}


/*
EXAMPLE:
+) Using JSONP to circumvent cross-domain restrictions and processing the result
*/
+) HTML
<div id="result"></div>

+)
function addScript( url) {
	var script = document.createElement('script');
	script.src = url;
	document.getElementsByTagName('head')[0].appendChild(script);
}

addScript('https://api.flickr.com/services/rest/?method=flickr.photos.search
&user_id=NSID&api_key=yourapikey&page=1&format=json&jsoncallback=processPhotos');

// assign photos globally, call first to load
function processPhotos(obj) {
	photos = obj.photos.photo;
	var str = '';
	
	photos.forEach(function(photo) {
		str += photo.title + '<br /> ';
	});
	document.getElementById('result').innerHTML = str;
}